import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'am';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.eeg': 'EEG Technology',
    'nav.services': 'Services',
    'nav.doctors': 'Doctors',
    'nav.portal': 'Patient Portal',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.book': 'Book Appointment',
    'common.clinicName': 'YEHULESHET SPECIALITY CLINIC',
    'common.certified': 'Certified Specialists',
    'common.modern': 'Modern Equipment',
    'common.neurology': 'Neurology',
    'common.expertCare': 'Expert Care',
    'common.specialized': 'Specialized treatments for complex neurological conditions and brain health.',
    'common.respected': "Our clinic is home to some of the region's most respected neurological experts, dedicated to providing exceptional care.",
    'doctors.d1.specialty': 'Epilepsy & EEG Specialist',
    'doctors.d2.specialty': 'Spinal & Cranial Surgery',
    'doctors.d3.specialty': 'Nerve & Muscle Disorders',
    'hero.title': 'Advanced Neurological Care for a Better Life',
    'hero.subtitle': 'Leading the way in neurology, nerve care, and neurosurgery with state-of-the-art EEG technology and compassionate expertise.',
    'hero.cta.book': 'Book Appointment',
    'hero.cta.services': 'Our Services',
    'about.title': 'About YEHULESHET SPECIALITY CLINIC',
    'about.subtitle': 'Excellence in Neurological Care',
    'about.description': 'YEHULESHET SPECIALITY CLINIC is a leading medical facility in Addis Ababa, dedicated to providing world-class neurological care. Our team of experts specializes in neurology, neurosurgery, and nerve care, utilizing the latest medical technologies to ensure precise diagnostics and effective treatments.',
    'services.title': 'Our Specialized Services',
    'services.subtitle': 'Comprehensive Neurological Care',
    'doctors.title': 'Meet Our Specialists',
    'doctors.subtitle': 'Expert Neurologists & Surgeons',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find Answers to Common Queries',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'We are Here to Help You',
    'footer.description': 'Leading the way in advanced neurology, nerve care, and neurosurgery. Dedicated to providing precise diagnostics and compassionate treatment for all neurological conditions.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.contact': 'Contact Info',
    'footer.rights': '© 2026 YEHULESHET SPECIALITY CLINIC. All rights reserved.',
    'eeg.badge': 'Advanced Technology',
    'eeg.title': 'State-of-the-Art EEG Brain Mapping',
    'eeg.description': "Our new Electroencephalogram (EEG) machine represents the pinnacle of diagnostic neurology, allowing us to see your brain's health in real-time.",
    'eeg.whatIs': 'What is an EEG?',
    'eeg.whatIsDesc': 'An Electroencephalogram (EEG) is a sophisticated test that detects and records the electrical activity of your brain. Using small, metal discs (electrodes) attached to your scalp, it tracks the communication between brain cells via electrical impulses.',
    'eeg.nonInvasive': 'Non-Invasive',
    'eeg.nonInvasiveDesc': 'No needles or pain involved.',
    'eeg.realTime': 'Real-Time',
    'eeg.realTimeDesc': 'Captures brain activity as it happens.',
    'eeg.diagnosticPower': 'Diagnostic Power',
    'eeg.diagnosticPowerDesc': 'Essential for epilepsy, sleep disorders, and more.',
    'eeg.benefit1.title': 'Accurate Diagnosis',
    'eeg.benefit1.desc': 'Precisely identifies abnormal brain waves associated with various conditions.',
    'eeg.benefit2.title': 'Early Detection',
    'eeg.benefit2.desc': 'Detects subtle changes in brain activity before symptoms become severe.',
    'eeg.benefit3.title': 'Safe & Non-Invasive',
    'eeg.benefit3.desc': 'A completely painless procedure with no side effects or radiation.',
    'eeg.benefit4.title': 'Better Planning',
    'eeg.benefit4.desc': 'Helps our specialists create highly targeted treatment strategies.',
    'eeg.howItWorks.title': 'How the EEG Procedure Works',
    'eeg.howItWorks.desc': "The process is simple and comfortable. You'll relax in a reclining chair while our technician applies electrodes to your scalp. The machine then records your brain waves while you rest or perform simple tasks.",
    'eeg.step1': '1. Preparation (15 min)',
    'eeg.step2': '2. Recording (20-40 min)',
    'eeg.step3': '3. Analysis (Expert Review)',
    'eeg.cta': 'Schedule a Test',
    'why.badge': 'Why Choose Us',
    'why.title': 'Setting the Standard in Brain Health',
    'why.description': 'We combine medical excellence with a compassionate approach to ensure you receive the best possible care for your neurological health.',
    'why.feat1.title': 'Specialized Neurology Expertise',
    'why.feat1.desc': 'Our board-certified neurologists bring decades of experience in treating complex brain disorders.',
    'why.feat2.title': 'Advanced Neurosurgical Support',
    'why.feat2.desc': 'State-of-the-art surgical interventions for spinal and cranial conditions with high success rates.',
    'why.feat3.title': 'Modern Diagnostic Technology',
    'why.feat3.desc': 'Equipped with the latest EEG, EMG, and imaging systems for pinpoint diagnostic accuracy.',
    'why.feat4.title': 'Experienced Medical Team',
    'why.feat4.desc': 'A collaborative team of specialists, nurses, and technicians dedicated to your recovery.',
    'why.feat5.title': 'Patient-Centered Care',
    'why.feat5.desc': 'We treat the person, not just the symptoms, with personalized care plans for every patient.',
    'why.feat6.title': 'Trusted Clinical Environment',
    'why.feat6.desc': 'A clean, modern, and reassuring facility designed for patient comfort and safety.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To provide accessible, high-quality neurological and neurosurgical care through advanced diagnostics and compassionate treatment.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be the leading center of excellence in brain and nerve health, recognized for innovation and patient-centered outcomes.',
    'about.values.title': 'Core Values',
    'about.values.desc': "Integrity, Excellence, Compassion, and Innovation guide every decision we make for our patients' well-being.",
    'about.check1': 'Expert Neurologists & Surgeons',
    'about.check2': 'Advanced Diagnostic Facilities',
    'about.check3': 'Personalized Treatment Plans',
    'about.check4': 'Compassionate Patient Care',
    'common.learnMore': 'Learn More',
    'services.desc': 'We offer a full spectrum of neurological services, from initial diagnosis to advanced surgical interventions.',
    'services.s1.title': 'Neurology Consultation',
    'services.s1.desc': 'Expert evaluation and management of headaches, epilepsy, stroke, and movement disorders.',
    'services.s2.title': 'Neurosurgery Consultation',
    'services.s2.desc': 'Specialized surgical assessments for brain tumors, spinal disorders, and nerve injuries.',
    'services.s3.title': 'EEG Brain Testing',
    'services.s3.desc': 'Advanced brain wave monitoring to diagnose seizures, sleep disorders, and brain function.',
    'services.s4.title': 'Nerve Assessment',
    'services.s4.desc': 'Comprehensive testing for peripheral nerve issues, neuropathy, and muscle weakness.',
    'services.s5.title': 'Brain & Nerve Diagnostics',
    'services.s5.desc': 'Utilizing modern imaging and diagnostic tools for precise identification of neurological issues.',
    'services.s6.title': 'Specialist Follow-Up Care',
    'services.s6.desc': 'Dedicated long-term management and rehabilitation support for chronic neurological conditions.',
    'doctors.d1.name': 'Dr. Mhila Zebenigus',
    'doctors.d1.role': 'Senior Neurologist',
    'doctors.d1.desc': 'Specializing in complex neurological disorders and EEG diagnostics with over 15 years of experience.',
    'doctors.d2.name': 'Dr. Abebe M.',
    'doctors.d2.role': 'Consultant Neurosurgeon',
    'doctors.d2.desc': 'Expert in spinal surgery and cranial interventions using minimally invasive techniques.',
    'doctors.d3.name': 'Dr. Selam W.',
    'doctors.d3.role': 'Nerve Specialist',
    'doctors.d3.desc': 'Dedicated to peripheral nerve health and rehabilitation for patients with chronic conditions.',
    'faq.q1': 'What should I bring to my first appointment?',
    'faq.a1': 'Please bring your ID, any previous medical records, imaging results (CDs/films), and a list of current medications.',
    'faq.q2': 'Is an EEG procedure painful?',
    'faq.a2': 'No, an EEG is a completely painless and non-invasive procedure. You will only feel the electrodes being placed on your scalp.',
    'faq.q3': 'How long does a typical consultation take?',
    'faq.a3': 'A typical initial consultation takes between 30 to 45 minutes, depending on the complexity of your condition.',
    'faq.q4': 'Do you accept insurance?',
    'faq.a4': 'Yes, we work with several major insurance providers. Please contact our office to verify your specific coverage.',
    'contact.info': 'Contact Information',
    'contact.address': 'Addis Ababa, Ethiopia',
    'contact.phone': 'Phone Number',
    'contact.email': 'Email Address',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message',
    'appointment.form.title': 'Request an Appointment',
    'appointment.form.desc': 'Fill out the form below and our team will contact you to confirm your visit.',
    'appointment.form.date': 'Preferred Date',
    'appointment.form.service': 'Select Service',
    'appointment.form.submit': 'Submit Request',
    'portal.badge': 'Patient Portal',
    'portal.title': 'Manage Your Health',
    'portal.titleAccent': 'Securely Online',
    'portal.description': 'Access your medical records, view test results (including EEG reports), and manage your appointments from our secure patient portal.',
    'portal.f1': 'View EEG & Diagnostic Reports',
    'portal.f2': 'Request Prescription Refills',
    'portal.f3': 'Secure Messaging with Doctors',
    'portal.f4': 'Appointment History & Reminders',
    'portal.login': 'Login',
    'portal.signup': 'Sign Up',
    'portal.emailPhone': 'Email or Phone',
    'portal.emailPhonePlaceholder': 'Enter your email or phone',
    'portal.password': 'Password',
    'portal.forgot': 'Forgot Password?',
    'portal.remember': 'Remember Me',
    'portal.loginBtn': 'Login to Portal',
    'portal.fullName': 'Full Name',
    'portal.email': 'Email Address',
    'portal.phone': 'Phone Number',
    'portal.confirm': 'Confirm',
    'portal.createBtn': 'Create Account',
    'contact.phoneLabel': 'Phone',
    'contact.emailLabel': 'Email',
    'contact.locationLabel': 'Our Location',
    'contact.hoursLabel': 'Working Hours',
    'contact.hoursDetails': 'Mon - Sat: 08:00 - 19:00',
    'contact.hoursSub': 'Sun: Closed (Emergency Only)',
    'contact.description': 'Have questions about our services or need to schedule a visit? Reach out to our team today. We\'re dedicated to providing you with the support you need.',
    'contact.callNow': 'Call Now',
    'contact.getDirections': 'Get Directions',
    'contact.mapPlaceholder': 'Google Map Placeholder',
    'contact.mapDescription': 'Our clinic is conveniently located on Bole Road, Addis Ababa.',
    'test.badge': 'Testimonials',
    'test.title': 'What Our',
    'test.titleAccent': 'Patients Say',
    'test.t1.name': 'Abebe Kebede',
    'test.t1.role': 'Patient',
    'test.t1.content': 'The EEG test was so professional and painless. Dr. Samuel explained the results in a way I could finally understand. I feel much better knowing the exact cause of my symptoms.',
    'test.t2.name': 'Selamawit Hailu',
    'test.t2.role': 'Patient',
    'test.t2.content': 'I\'ve visited many clinics for my chronic migraines, but the care at YEHULESHET SPECIALITY CLINIC is different. They truly listen and use the best technology available. Highly recommended!',
    'test.t3.name': 'Dawit Mengistu',
    'test.t3.role': 'Patient',
    'test.t3.content': 'The neurosurgery team saved my life. Their expertise and the modern facilities gave me and my family great confidence during a very difficult time. Thank you!',
  },
  am: {
    'nav.home': 'መነሻ',
    'nav.about': 'ስለ እኛ',
    'nav.eeg': 'የኢኢጂ ቴክኖሎጂ',
    'nav.services': 'አገልግሎቶች',
    'nav.doctors': 'ዶክተሮች',
    'nav.portal': 'የታካሚ ፖርታል',
    'nav.faq': 'ተደጋጋሚ ጥያቄዎች',
    'nav.contact': 'እውቂያ',
    'nav.book': 'ቀጠሮ ይያዙ',
    'common.clinicName': 'የሁሉሸት ልዩ ክሊኒክ',
    'common.certified': 'የተረጋገጡ ስፔሻሊስቶች',
    'common.modern': 'ዘመናዊ መሣሪያዎች',
    'common.neurology': 'የነርቭ ሕክምና',
    'common.expertCare': 'ባለሙያ እንክብካቤ',
    'common.specialized': 'ለተወሳሰቡ የነርቭ ሁኔታዎች እና ለአንጎል ጤና ልዩ ሕክምናዎች።',
    'common.respected': 'ክሊኒካችን በክልሉ ውስጥ ካሉ በጣም የተከበሩ የነርቭ ባለሙያዎች መኖሪያ ሲሆን ልዩ እንክብካቤ ለመስጠት የተሰጠ ነው።',
    'doctors.d1.specialty': 'የሚጥል በሽታ እና የኢኢጂ ስፔሻሊስት',
    'doctors.d2.specialty': 'የአከርካሪ እና የጭንቅላት ቀዶ ጥገና',
    'doctors.d3.specialty': 'የነርቭ እና የጡንቻ መዛባት',
    'hero.title': 'ለተሻለ ሕይወት የላቀ የነርቭ ሕክምና',
    'hero.subtitle': 'በነርቭ ሕክምና፣ በነርቭ እንክብካቤ እና በነርቭ ቀዶ ጥገና በዘመናዊ የኢኢጂ ቴክኖሎጂ እና በርህራሄ የተሞላ ሙያዊ ብቃት ግንባር ቀደም ነን።',
    'hero.cta.book': 'ቀጠሮ ይያዙ',
    'hero.cta.services': 'አገልግሎቶቻችን',
    'about.title': 'ስለ የሁሉሸት ልዩ ክሊኒክ',
    'about.subtitle': 'በነርቭ ሕክምና የላቀ ብቃት',
    'about.description': 'የሁሉሸት ልዩ ክሊኒክ በአዲስ አበባ ውስጥ የሚገኝ ግንባር ቀደም የሕክምና ተቋም ሲሆን በዓለም አቀፍ ደረጃ የነርቭ ሕክምናን ለመስጠት የተሰጠ ነው። ቡድናችን በነርቭ ሕክምና፣ በነርቭ ቀዶ ጥገና እና በነርቭ እንክብካቤ ላይ የተካነ ሲሆን ትክክለኛ ምርመራዎችን እና ውጤታማ ሕክምናዎችን ለማረጋገጥ የቅርብ ጊዜ የሕክምና ቴክኖሎጂዎችን ይጠቀማል።',
    'services.title': 'የእኛ ልዩ አገልግሎቶች',
    'services.subtitle': 'አጠቃላይ የነርቭ ሕክምና',
    'doctors.title': 'የእኛን ስፔሻሊስቶች ያግኙ',
    'doctors.subtitle': 'ባለሙያ የነርቭ ሐኪሞች እና የቀዶ ጥገና ሐኪሞች',
    'faq.title': 'ተደጋጋሚ ጥያቄዎች',
    'faq.subtitle': 'ለተለመዱ ጥያቄዎች መልስ ያግኙ',
    'contact.title': 'እውቂያ ያድርጉ',
    'contact.subtitle': 'እርስዎን ለመርዳት እዚህ ነን',
    'footer.description': 'በላቀ የነርቭ ሕክምና፣ በነርቭ እንክብካቤ እና በነርቭ ቀዶ ጥገና ግንባር ቀደም። ለሁሉም የነርቭ ሁኔታዎች ትክክለኛ ምርመራ እና አዛኝ ሕክምና ለመስጠት የተሰጠ።',
    'footer.quickLinks': 'ፈጣን አገናኞች',
    'footer.services': 'አገልግሎቶቻችን',
    'footer.contact': 'የእውቂያ መረጃ',
    'footer.rights': '© 2026 የሁሉሸት ልዩ ክሊኒክ። መብቱ በህግ የተጠበቀ ነው።',
    'eeg.badge': 'የላቀ ቴክኖሎጂ',
    'eeg.title': 'ዘመናዊ የኢኢጂ (EEG) የአንጎል ካርታ ስራ',
    'eeg.description': 'አዲሱ የኢኢጂ (EEG) ማሽናችን የአንጎልዎን ጤና በቅጽበት ለማየት የሚያስችለን የነርቭ ምርመራ ከፍተኛ ደረጃን ይወክላል።',
    'eeg.whatIs': 'ኢኢጂ (EEG) ምንድን ነው?',
    'eeg.whatIsDesc': 'ኢኢጂ (EEG) የአንጎልዎን የኤሌክትሪክ እንቅስቃሴ የሚለካ እና የሚመዘግብ የተራቀቀ ምርመራ ነው። በጭንቅላትዎ ላይ የሚጣበቁ ትናንሽ የብረት ዲስኮች (ኤሌክትሮዶች) በመጠቀም በአንጎል ሴሎች መካከል ያለውን ግንኙነት በኤሌክትሪክ ግፊቶች ይከታተላል።',
    'eeg.nonInvasive': 'ወራሪ ያልሆነ',
    'eeg.nonInvasiveDesc': 'መርፌ ወይም ህመም የለውም።',
    'eeg.realTime': 'በቅጽበት',
    'eeg.realTimeDesc': 'የአንጎል እንቅስቃሴን በሚከሰትበት ጊዜ ይይዛል።',
    'eeg.diagnosticPower': 'የምርመራ አቅም',
    'eeg.diagnosticPowerDesc': 'ለሚጥል በሽታ፣ ለእንቅልፍ መዛባት እና ለሌሎችም አስፈላጊ ነው።',
    'eeg.benefit1.title': 'ትክክለኛ ምርመራ',
    'eeg.benefit1.desc': 'ከተለያዩ ሁኔታዎች ጋር የተያያዙ ያልተለመዱ የአንጎል ሞገዶችን በትክክል ይለያል።',
    'eeg.benefit2.title': 'ቀደም ብሎ መለየት',
    'eeg.benefit2.desc': 'ምልክቶቹ ከመባባሳቸው በፊት በአንጎል እንቅስቃሴ ላይ ጥቃቅን ለውጦችን ያውቃል።',
    'eeg.benefit3.title': 'አስተማማኝ እና ወራሪ ያልሆነ',
    'eeg.benefit3.desc': 'ምንም ዓይነት የጎንዮሽ ጉዳት ወይም ጨረር የሌለው ሙሉ በሙሉ ህመም የሌለበት ሂደት።',
    'eeg.benefit4.title': 'የተሻለ እቅድ',
    'eeg.benefit4.desc': 'ባለሙያዎቻችን ከፍተኛ ትኩረት የተሰጣቸው የሕክምና ስልቶችን እንዲነድፉ ይረዳል።',
    'eeg.howItWorks.title': 'የኢኢጂ (EEG) ሂደት እንዴት እንደሚሰራ',
    'eeg.howItWorks.desc': 'ሂደቱ ቀላል እና ምቹ ነው። የእኛ ባለሙያ በጭንቅላትዎ ላይ ኤሌክትሮዶችን ሲያደርግ እርስዎ ዘና ብለው ይቀመጣሉ። ከዚያም እርስዎ በሚያርፉበት ወይም ቀላል ስራዎችን በሚሰሩበት ጊዜ ማሽኑ የአንጎልዎን ሞገዶች ይመዘግባል።',
    'eeg.step1': '1. ዝግጅት (15 ደቂቃ)',
    'eeg.step2': '2. ቀረጻ (20-40 ደቂቃ)',
    'eeg.step3': '3. ትንተና (የባለሙያ ግምገማ)',
    'eeg.cta': 'ምርመራ ቀጠሮ ይያዙ',
    'why.badge': 'ለምን እኛን ይመርጣሉ?',
    'why.title': 'በአንጎል ጤና ላይ ደረጃውን የጠበቀ አገልግሎት',
    'why.description': 'ለነርቭ ጤናዎ የተሻለውን እንክብካቤ እንዲያገኙ ለማረጋገጥ የሕክምና የላቀ ብቃትን ከአዛኝ አቀራረብ ጋር እናጣምራለን።',
    'why.feat1.title': 'ልዩ የነርቭ ሕክምና ሙያዊ ብቃት',
    'why.feat1.desc': 'የእኛ የነርቭ ሐኪሞች ውስብስብ የአንጎል በሽታዎችን በማከም ረገድ የአስርተ ዓመታት ልምድ አላቸው።',
    'why.feat2.title': 'የላቀ የነርቭ ቀዶ ጥገና ድጋፍ',
    'why.feat2.desc': 'ለአከርካሪ እና ለጭንቅላት ሁኔታዎች ከፍተኛ ስኬት ያላቸው ዘመናዊ የቀዶ ጥገና ጣልቃገብነቶች።',
    'why.feat3.title': 'ዘመናዊ የምርመራ ቴክኖሎጂ',
    'why.feat3.desc': 'ለትክክለኛ የምርመራ ውጤት የቅርብ ጊዜዎቹ የኢኢጂ (EEG)፣ የኢኤምጂ (EMG) እና የምስል ስርዓቶች የታጠቁ።',
    'why.feat4.title': 'ልምድ ያለው የሕክምና ቡድን',
    'why.feat4.desc': 'ለእርስዎ ማገገም የተሰጡ የልዩ ባለሙያዎች፣ የነርሶች እና የቴክኒሻኖች የጋራ ቡድን።',
    'why.feat5.title': 'በታካሚ ላይ ያተኮረ እንክብካቤ',
    'why.feat5.desc': 'ለእያንዳንዱ ታካሚ ግላዊ የሕክምና ዕቅዶችን በማዘጋጀት ምልክቶቹን ብቻ ሳይሆን ሰውን እናክማለን።',
    'why.feat6.title': 'የታመነ የክሊኒክ አካባቢ',
    'why.feat6.desc': 'ለታካሚ ምቾት እና ደህንነት ተብሎ የተነደፈ ንጹህ፣ ዘመናዊ እና የሚያረጋጋ ተቋም።',
    'about.mission.title': 'ተልእኳችን',
    'about.mission.desc': 'በላቀ ምርመራ and አዛኝ ሕክምና አማካኝነት ተደራሽ እና ጥራት ያለው የነርቭ ሕክምና እና የነርቭ ቀዶ ጥገና አገልግሎት መስጠት።',
    'about.vision.title': 'ራእያችን',
    'about.vision.desc': 'በፈጠራ እና በታካሚ ላይ ያተኮሩ ውጤቶች የሚታወቅ የአንጎል እና የነርቭ ጤና ግንባር ቀደም የላቀ ማዕከል መሆን።',
    'about.values.title': 'እሴቶቻችን',
    'about.values.desc': 'ታማኝነት፣ የላቀ ብቃት፣ ርህራሄ እና ፈጠራ ለእያንዳንዱ የታካሚዎቻችን ደህንነት የምናደርገውን ውሳኔ ይመራሉ።',
    'about.check1': 'ባለሙያ የነርቭ ሐኪሞች እና የቀዶ ጥገና ሐኪሞች',
    'about.check2': 'የላቀ የምርመራ ተቋማት',
    'about.check3': 'ግላዊ የሕክምና ዕቅዶች',
    'about.check4': 'አዛኝ የታካሚ እንክካቤ',
    'common.learnMore': 'የበለጠ ይረዱ',
    'services.desc': 'ከመጀመሪያው ምርመራ እስከ ከፍተኛ የቀዶ ጥገና ጣልቃገብነት ድረስ ሙሉ የነርቭ አገልግሎቶችን እንሰጣለን።',
    'services.s1.title': 'የነርቭ ሕክምና ምክክር',
    'services.s1.desc': 'የራስ ምታት፣ የሚጥል በሽታ፣ ስትሮክ እና የእንቅስቃሴ መዛባት ባለሙያ ግምገማ እና አያያዝ።',
    'services.s2.title': 'የነርቭ ቀዶ ጥገና ምክክር',
    'services.s2.desc': 'ለአንጎል እጢዎች፣ ለአከርካሪ መዛባት እና ለነርቭ ጉዳቶች ልዩ የቀዶ ጥገና ግምገማዎች።',
    'services.s3.title': 'የኢኢጂ (EEG) የአንጎል ምርመራ',
    'services.s3.desc': 'የሚጥል በሽታን፣ የእንቅልፍ መዛባትን እና የአንጎልን ተግባር ለመመርመር የላቀ የአንጎል ሞገድ ክትትል::',
    'services.s4.title': 'የነርቭ ግምገማ',
    'services.s4.desc': 'ለአካባቢያዊ የነርቭ ችግሮች፣ ለኒውሮፓቲ እና ለጡንቻ ድክመት አጠቃላይ ምርመራ።',
    'services.s5.title': 'የአንጎል እና የነርቭ ምርመራዎች',
    'services.s5.desc': 'የነርቭ ችግሮችን በትክክል ለመለየት ዘመናዊ የምስል እና የምርመራ መሳሪያዎችን መጠቀም።',
    'services.s6.title': 'የልዩ ባለሙያ ክትትል እንክብካቤ',
    'services.s6.desc': 'ለከባድ የነርቭ ሁኔታዎች የረጅም ጊዜ አስተዳደር እና የመልሶ ማቋቋም ድጋፍ።',
    'doctors.d1.name': 'ዶ/ር ምህላ ዘበኒጉስ',
    'doctors.d1.role': 'ከፍተኛ የነርቭ ሐኪም',
    'doctors.d1.desc': 'ከ15 ዓመታት በላይ ልምድ ያላቸው ውስብስብ የነርቭ በሽታዎች እና የኢኢጂ (EEG) ምርመራ ባለሙያ።',
    'doctors.d2.name': 'ዶ/ር አበበ ኤም.',
    'doctors.d2.role': 'አማካሪ የነርቭ ቀዶ ጥገና ሐኪም',
    'doctors.d2.desc': 'በትንሽ ቀዶ ጥገና ዘዴዎችን በመጠቀም የአከርካሪ ቀዶ ጥገና እና የጭንቅላት ጣልቃገብነት ባለሙያ።',
    'doctors.d3.name': 'ዶ/ር ሰላም ደብሊው.',
    'doctors.d3.role': 'የነርቭ ስፔሻሊስት',
    'doctors.d3.desc': 'ለከባድ ህመም ላለባቸው ታካሚዎች ለአካባቢያዊ የነርቭ ጤና እና መልሶ ማቋቋም የተሰጡ።',
    'faq.q1': 'ለመጀመሪያው ቀጠሮ ምን ይዤ መምጣት አለብኝ?',
    'faq.a1': 'እባክዎን መታወቂያዎን፣ ማንኛውንም የቀድሞ የሕክምና መዝገቦችን፣ የምስል ውጤቶችን (ሲዲዎች/ፊልሞች) እና የአሁኑን መድሃኒቶች ዝርዝር ይዘው ይምጡ።',
    'faq.q2': 'የኢኢጂ (EEG) ሂደት ህመም አለው?',
    'faq.a2': 'አይ፣ ኢኢጂ (EEG) ሙሉ በሙሉ ህመም የሌለበት እና ወራሪ ያልሆነ ሂደት ነው። ኤሌክትሮዶቹ በጭንቅላትዎ ላይ ሲቀመጡ ብቻ ነው የሚሰማዎት።',
    'faq.q3': 'የተለመደው ምክክር ምን ያህል ጊዜ ይወስዳል?',
    'faq.a3': 'እንደ ሁኔታዎ ውስብስብነት አንድ የተለመደ የመጀመሪያ ምክክር ከ30 እስከ 45 ደቂቃዎች ይወስዳል።',
    'faq.q4': 'ኢንሹራንስ ይቀበላሉ?',
    'faq.a4': 'አዎ፣ ከበርካታ ዋና ዋና የኢንሹራንስ አቅራቢዎች ጋር እንሰራለን። እባክዎን የእርስዎን ልዩ ሽፋን ለማረጋገጥ ቢሮአችንን ያነጋግሩ።',
    'contact.info': 'የእውቂያ መረጃ',
    'contact.address': 'አዲስ አበባ፣ ኢትዮጵያ',
    'contact.phone': 'የስልክ ቁጥር',
    'contact.email': 'የኢሜል አድራሻ',
    'contact.form.name': 'ሙሉ ስም',
    'contact.form.email': 'የኢሜል አድራሻ',
    'contact.form.subject': 'ርዕሰ ጉዳይ',
    'contact.form.message': 'የእርስዎ መልዕክት',
    'contact.form.send': 'መልዕክት ላክ',
    'appointment.form.title': 'ቀጠሮ ይጠይቁ',
    'appointment.form.desc': 'ከዚህ በታች ያለውን ቅጽ ይሙሉ እና ቡድናችን ጉብኝትዎን ለማረጋገጥ ያነጋግርዎታል።',
    'appointment.form.date': 'ተመራጭ ቀን',
    'appointment.form.service': 'አገልግሎት ይምረጡ',
    'appointment.form.submit': 'ጥያቄውን ያቅርቡ',
    'portal.badge': 'የታካሚ ፖርታል',
    'portal.title': 'ጤናዎን ያስተዳድሩ',
    'portal.titleAccent': 'በደህንነት በመስመር ላይ',
    'portal.description': 'የሕክምና መዝገቦችዎን ይድረሱ፣ የምርመራ ውጤቶችን (የኢኢጂ ሪፖርቶችን ጨምሮ) ይመልከቱ እና ቀጠሮዎችዎን ከደህንነቱ የታካሚ ፖርታል ያስተዳድሩ።',
    'portal.f1': 'የኢኢጂ እና የምርመራ ሪፖርቶችን ይመልከቱ',
    'portal.f2': 'የመድኃኒት ማዘዣ እድሳትን ይጠይቁ',
    'portal.f3': 'ከዶክተሮች ጋር ደህንነቱ የተጠበቀ መልዕክት',
    'portal.f4': 'የቀጠሮ ታሪክ እና ማሳሰቢያዎች',
    'portal.login': 'ግባ',
    'portal.signup': 'ተመዝገብ',
    'portal.emailPhone': 'ኢሜል ወይም ስልክ',
    'portal.emailPhonePlaceholder': 'ኢሜልዎን ወይም ስልክዎን ያስገቡ',
    'portal.password': 'የይለፍ ቃል',
    'portal.forgot': 'የይለፍ ቃል ረሱ?',
    'portal.remember': 'አስታውሰኝ',
    'portal.loginBtn': 'ወደ ፖርታል ግባ',
    'portal.fullName': 'ሙሉ ስም',
    'portal.email': 'የኢሜል አድራሻ',
    'portal.phone': 'የስልክ ቁጥር',
    'portal.confirm': 'አረጋግጥ',
    'portal.createBtn': 'መለያ ፍጠር',
    'contact.phoneLabel': 'ስልክ',
    'contact.emailLabel': 'ኢሜል',
    'contact.locationLabel': 'የእኛ ቦታ',
    'contact.hoursLabel': 'የስራ ሰዓታት',
    'contact.hoursDetails': 'ከሰኞ - ቅዳሜ፡ 02:00 - 13:00',
    'contact.hoursSub': 'እሁድ፡ ዝግ ነው (ለአደጋ ጊዜ ብቻ)',
    'contact.description': 'ስለ አገልግሎቶቻችን ጥያቄዎች አሉዎት ወይስ ጉብኝት ለማስያዝ ይፈልጋሉ? ዛሬውኑ ቡድናችንን ያነጋግሩ። የሚፈልጉትን ድጋፍ ለመስጠት ቆርጠን ተነስተናል።',
    'contact.callNow': 'አሁን ይደውሉ',
    'contact.getDirections': 'አቅጣጫዎችን ያግኙ',
    'contact.mapPlaceholder': 'የጉግል ካርታ ቦታ',
    'contact.mapDescription': 'ክሊኒካችን በአዲስ አበባ ቦሌ መንገድ ላይ በሚመች ሁኔታ ይገኛል።',
    'test.badge': 'ምስክርነቶች',
    'test.title': 'ታካሚዎቻችን',
    'test.titleAccent': 'ምን ይላሉ',
    'test.t1.name': 'አበበ ከበደ',
    'test.t1.role': 'ታካሚ',
    'test.t1.content': 'የኢኢጂ ምርመራው በጣም ሙያዊ እና ህመም የሌለው ነበር። ዶ/ር ሳሙኤል ውጤቱን በመጨረሻ ልረዳው በምችልበት መንገድ አብራርተውልኛል። የሕመሜን ትክክለኛ መንስኤ በማወቄ በጣም ጥሩ ስሜት ይሰማኛል።',
    'test.t2.name': 'ሰላማዊት ኃይሉ',
    'test.t2.role': 'ታካሚ',
    'test.t2.content': 'ለከባድ ራስ ምታቴ ብዙ ክሊኒኮችን ጎብኝቻለሁ፣ ነገር ግን በየሁሉሸት ልዩ ክሊኒክ የሚደረገው እንክብካቤ የተለየ ነው። በእውነት ያዳምጣሉ እና ያሉትን ምርጥ ቴክኖሎጂዎች ይጠቀማሉ። በጣም የሚመከር!',
    'test.t3.name': 'ዳዊት መንግስቱ',
    'test.t3.role': 'ታካሚ',
    'test.t3.content': 'የነርቭ ቀዶ ጥገና ቡድኑ ህይወቴን አድኖታል። የእነሱ እውቀት እና ዘመናዊ መገልገያዎች በጣም አስቸጋሪ በሆነ ጊዜ ለእኔ እና ለቤተሰቤ ትልቅ እምነት ሰጥተውናል። አመሰግናለሁ!',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
